{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "1ff2891c",
   "metadata": {},
   "source": [
    "\n",
    "<div align=\"center\" style=\"font-family: times, serif; font-size:18pt; font-style:italic; \" >   Universidad Laica “Eloy Alfaro” de Manabí</div><br>\n",
    "<div align=\"center\" style=\"font-family: times, serif; font-size:15pt; font-style:italic; \" > Facultad de Ciencias Informáticas    </div><br>\n",
    "<div align=\"center\" style=\"font-family: times, serif; font-size:15pt; font-style:italic; \" > CARRERA DE TECNOLOGÍA DE LA INFORMACIÓN   </div><br>\n",
    "<div align=\"center\" style=\"font-family: times, serif; font-size:15pt; font-style:italic; \" > TAREA PARCIAL 2   </div><br>\n",
    "\n",
    "<div align=\"center\" style=\"font-family: times, serif; font-size:15pt; font-style:italic; \" > DESCRIPCIÓN:Trabajo Práctico en python</div><br>\n",
    "\n",
    "<div align=\"center\" style=\"font-family: times, serif; font-size:15pt; font-style:italic; \" > DOCENTE: ING. CARLOS XAVIER AVILA PACHAY   </div><br>\n",
    "\n",
    "<div align=\"center\" style=\"font-family: times, serif; font-size:15pt; font-style:italic; \" > ASIGNATURA: INTELIGENCIA ARTIFICIAL </div><br>\n",
    "\n",
    "\n",
    "<div align=\"center\" style=\"font-family: times, serif; font-size:15pt; font-style:italic; \" > CURSO: 8 \"B\"   </div><br>\n",
    "\n",
    "<div align=\"center\" style=\"font-family: times, serif; font-size:15pt; font-style:italic; \" > FECHA DE ENTREGA: 26/06/2022  </div><br>\n",
    "\n",
    "<div align=\"center\" style=\"font-family: times, serif; font-size:15pt; font-style:italic; \" > PERÍODO: 2022(2)</div><br>\n",
    "\n",
    "<div align=\"center\" style=\"font-family: times, serif; font-size:15pt; font-style:italic; \" >Manta - Manabí – Ecuador </div> "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "90a8d3c2",
   "metadata": {},
   "source": [
    "## EJERCICIO NÚMERO 1\n",
    "\n",
    "\n",
    "Ingresar N personas, en cada uno tiene que ingresar su respectivo valores en Talla, Peso, considere decimales.\n",
    "\n",
    "Calcular su Índice Masa Corporal. Aplique la formula del IMC.\n",
    "\n",
    "Validar el resultado del IMC, represente su condición\n",
    "\n",
    "IMC<18,5;\"Bajo peso\";\n",
    "\n",
    "IMC>=18,5 AND IMC<=24,9;\"Normal\";\n",
    "\n",
    "IMC>=25 AND IMC <=29,9\"Sobrepeso\";\n",
    "\n",
    "IMC>=30 AND IMC <=34,9)\"Obesidad Grado I\n",
    "\n",
    "IMC>=35 AND IMC<=39,9)\"Obesidad Grado II\"\n",
    "\n",
    "IMC>=40;\"Obesidad Grado III\"\n",
    "\n",
    "Una vez validado contar los respectivos resultados, Se pide mostrar los resultados en cada criterio o validación. Utilice las respectivas sentencencias, funciones en Python"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7f27fac6",
   "metadata": {},
   "outputs": [],
   "source": [
    "peso = float(input(\"Ingrese el peso de la persona(kg)\"))\n",
    "altura = float(input(\"Ingrese la altura de la persona(m)\"))\n",
    "\n",
    "\n",
    "\n",
    "valor  = peso / (altura*altura) \n",
    "\n",
    "print(\"\\n ----RESULTADO DEL ICM----\")\n",
    "\n",
    "while(valor<=18.5):\n",
    "            print(\"bajo peso\")\n",
    "            break\n",
    "        \n",
    "        \n",
    "while(valor>=18.5 and  valor<=24.9):\n",
    "            print(\"Normal\")\n",
    "            break\n",
    "               \n",
    "while(valor>=25 and  valor<=29.9):\n",
    "            print(\"Sobrepeso\")\n",
    "            break\n",
    "               \n",
    "while(valor>=30 and  valor<=34.9):\n",
    "            print(\"Obesidad Grado I\")\n",
    "            break\n",
    "\n",
    "while(valor>=35 and  valor<=39.9):\n",
    "            print(\"Obesidad Grado II\")\n",
    "            break\n",
    "\n",
    "               \n",
    "while(valor>=35 and valor<=39.9):\n",
    "            print(\"Obesidad Grado II\")\n",
    "            break\n",
    "\n",
    "               \n",
    "while(valor>=40):\n",
    "            print(\"Obesidad Grado II\")\n",
    "            break\n",
    "               \n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ba67af6b",
   "metadata": {},
   "source": [
    "## EJERCICIO NÚMERO 2\n",
    "\n",
    "\n",
    "Ingrese valores en el arreglo\n",
    "\n",
    "Se pide como proceso SUMAR Y CALCULAR EL PROMEDIO de los valores que contiene el vector, en posiciones impares. \n",
    "Se pide como proceso SUMAR Y CALCULAR EL PROMEDIO los valores que contiene el vector en posiciones pares."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a9a33524",
   "metadata": {},
   "source": [
    "## EJERCICIO NÚMERO 3\n",
    "\n",
    "\n",
    "c.- Realice una estructura Switch con las opciones\n",
    "\n",
    "1.- Ingreso de N trabajadores con sus respectivos nombre, cargo, sueldo en un vector\n",
    "\n",
    "2.- Suma de los valores (columna sueldo) y mostrar el promedio\n",
    "\n",
    "3.- Sueldo mínimo y máximo (identificar el sueldo con sus respectivos datos (nombre, Cargo, Sueldo)\n",
    "\n",
    "4.- Mostrar los resultados (Número de personas ingresados con sus datos, promedio de los sueldos, Sueldo mínimo, máximo con sus datos)\n",
    "\n",
    "5.- Salir\n",
    "\n",
    "Nota para este ejercicio tome en cuenta al ingresar el numeral tiene que ser validado, en caso de que no sea el numeral de la opción, se vuelva a intentar hasta que sea correcto"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5c7868c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "def ingresar():\n",
    "            \n",
    "            global nombres\n",
    "            global sueldos\n",
    "            global identificaciones \n",
    "            global tamaño\n",
    "\n",
    "        \n",
    "            nombres = []\n",
    "            sueldos = []\n",
    "            identificaciones = []\n",
    "            \n",
    "         \n",
    "            # Definimos un tamaño para las listas\n",
    "            # Lo puedes cambiar si quieres\n",
    "            tamaño = int(input(\"ingrese el valor total de personas\"))\n",
    "\n",
    "            # Leemos los datos y los agregamos a la lista\n",
    "            for i in range(tamaño):\n",
    "                print(\"Ingrese los datos de la persona\", i + 1)\n",
    "                nombre = input(\"Nombre: \")\n",
    "                sueldo =  int(input(\"Sueldo: \"))\n",
    "                identificación = input(\"Cargo:\")\n",
    "\n",
    "                nombres.append(nombre)\n",
    "                sueldos.append(sueldo)\n",
    "                identificaciones.append(identificación)\n",
    "\n",
    "            # Ahora mostremos las listas\n",
    "            for i in range(tamaño):\n",
    "                print(\"Mostrando los datos de la persona\", i + 1)\n",
    "\n",
    "                print(\"Nombre:\", nombres[i])\n",
    "                print(\"Sueldo:\", sueldos[i])\n",
    "                print(\"Cargo:\", identificaciones[i]),\n",
    "                \n",
    "            \n",
    "            \n",
    "            \n",
    "            nummenu = int(input(\"INGRESE OPCION DE MENÚ \\n 1.INGRESAR PERSONAS \\n 2.CALCULAR PROMEDIO \\n 3.ENCONTRAR MAX Y MIN SUELDO \\n 4.MOSTRAR \\n 5.SALIR \\n INGRESE OPCION DEL MENU-->\"))\n",
    "            switch_semana.get(nummenu, error)()\n",
    "\n",
    "def calcularprom():\n",
    "            global listProm\n",
    "            listProm = sum(sueldos)\n",
    "            print(f\"Promedio sueldo de empleado -> {listProm/tamaño}\")\n",
    "            \n",
    "            nummenu = int(input(\"INGRESE OPCION DE MENÚ \\n 1.INGRESAR PERSONAS \\n 2.CALCULAR PROMEDIO \\n 3.ENCONTRAR MAX Y MIN SUELDO \\n 4.MOSTRAR \\n 5.SALIR \\n INGRESE OPCION DEL MENU-->\"))\n",
    "            switch_semana.get(nummenu, error)()\n",
    "            \n",
    "def calcularsueldomaxmin():\n",
    "            global maxSueldo\n",
    "            global minSueldo\n",
    "            maxSueldo = max(sueldos)\n",
    "            print(f\"Valor máximo del sueldo -> {maxSueldo}\")\n",
    "            indexpersonamaxsueldo= sueldos.index(maxSueldo)\n",
    "\n",
    "\n",
    "\n",
    "            print(\"---PERSONA CON MAXIMO SUELDO---\")\n",
    "            print(\"Nombre:\", nombres[indexpersonamaxsueldo])\n",
    "            print(\"Sueldo:\", sueldos[indexpersonamaxsueldo])\n",
    "            print(\"Cargo:\", identificaciones[indexpersonamaxsueldo])\n",
    "\n",
    "            minSueldo = min(sueldos)\n",
    "            print(f\"Valor mínimo del sueldo -> {minSueldo}\")\n",
    "            indexpersonaminsueldo= sueldos.index(minSueldo)\n",
    "\n",
    "            print(\"---PERSONA CON MINIMO SUELDO---\")\n",
    "            print(\"Nombre:\", nombres[indexpersonaminsueldo])\n",
    "            print(\"Sueldo:\", sueldos[indexpersonaminsueldo])\n",
    "            print(\"Cargo:\", identificaciones[indexpersonaminsueldo])\n",
    "            \n",
    "            nummenu = int(input(\"INGRESE OPCION DE MENÚ \\n 1.INGRESAR PERSONAS \\n 2.CALCULAR PROMEDIO \\n 3.ENCONTRAR MAX Y MIN SUELDO \\n 4.MOSTRAR \\n 5.SALIR \\n INGRESE OPCION DEL MENU-->\"))\n",
    "            switch_semana.get(nummenu, error)()\n",
    "            \n",
    "def mostrar():\n",
    "            print(\"------LISTADO DE PERSONAS--------\")\n",
    "            for i in range(tamaño):\n",
    "                   \n",
    "                    print(\"Mostrando los datos de la persona\", i + 1)\n",
    "\n",
    "                    print(\"Nombre:\", nombres[i])\n",
    "                    print(\"Sueldo:\", sueldos[i])\n",
    "                    print(\"Cargo:\", identificaciones[i])\n",
    "            print(\"---FIN LISTADO---\")\n",
    "            print(\"------PROMEDIO SUELDO DE LAS PERSONAS--------\")\n",
    "            print(f\"Promedio sueldo de empleado -> {listProm/tamaño}\")\n",
    "            \n",
    "            print(\"------MAXIMO Y MINIMO SUELDO DE LAS PERSONAS--------\")\n",
    "            print(f\"Valor máximo del sueldo -> {maxSueldo}\")\n",
    "            indexpersonamaxsueldo= sueldos.index(maxSueldo)\n",
    "\n",
    "            print(\"---PERSONA CON MAXIMO SUELDO---\")\n",
    "            print(\"Nombre:\", nombres[indexpersonamaxsueldo])\n",
    "            print(\"Sueldo:\", sueldos[indexpersonamaxsueldo])\n",
    "            print(\"Cargo:\", identificaciones[indexpersonamaxsueldo])\n",
    "            \n",
    "            print(f\"Valor mínimo del sueldo -> {minSueldo}\")\n",
    "            indexpersonaminsueldo= sueldos.index(minSueldo)\n",
    "\n",
    "            print(\"---PERSONA CON MINIMO SUELDO---\")\n",
    "            print(\"Nombre:\", nombres[indexpersonaminsueldo])\n",
    "            print(\"Sueldo:\", sueldos[indexpersonaminsueldo])\n",
    "            print(\"Cargo:\", identificaciones[indexpersonaminsueldo])\n",
    "            \n",
    "            nummenu = int(input(\"INGRESE OPCION DE MENÚ \\n 1.INGRESAR PERSONAS \\n 2.CALCULAR PROMEDIO \\n 3.ENCONTRAR MAX Y MIN SUELDO \\n 4.MOSTRAR \\n 5.SALIR \\n INGRESE OPCION DEL MENU-->\"))\n",
    "            switch_semana.get(nummenu, error)()\n",
    "\n",
    "            \n",
    "\n",
    "\n",
    "def salir():\n",
    "         \n",
    "            valor  = 1\n",
    "            while(valor >=1):\n",
    "                         print(\"Usted ha salido del menú\")\n",
    "                         break\n",
    "        \n",
    "        \n",
    "\n",
    "def error():\n",
    "    print('LA OPCION DE MENU QUE DIGISTASTE NO ES VALIDA, INTENTE DE NUEVO')\n",
    "    nummenu = int(input(\"INGRESE OPCION DE MENÚ \\n 1.INGRESAR PERSONAS \\n 2.CALCULAR PROMEDIO \\n 3.ENCONTRAR MAX Y MIN SUELDO \\n 4.MOSTRAR \\n 5.SALIR \\n INGRESE OPCION DEL MENU-->\"))\n",
    "    switch_semana.get(nummenu, error)()\n",
    "\n",
    "    \n",
    "\n",
    "\n",
    "switch_semana = {\n",
    "\t1: ingresar,\n",
    "\t2: calcularprom,\n",
    "\t3: calcularsueldomaxmin,\n",
    "\t4: mostrar,\n",
    "\t5: salir\n",
    "}\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "nummenu = int(input(\"INGRESE OPCION DE MENÚ \\n 1.INGRESAR PERSONAS \\n 2.CALCULAR PROMEDIO \\n 3.ENCONTRAR MAX Y MIN SUELDO \\n 4.MOSTRAR \\n 5.SALIR \\n INGRESE OPCION DEL MENU-->\"))\n",
    "\n",
    "\n",
    "#tomamos la función asociada a la variable y la invocamos\n",
    "switch_semana.get(nummenu, error)()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9336fe9b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
